version: '3.8'
services:
  db:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    network_mode: bridge

volumes:
  mongodb-data:
    driver: local
