version: '3'

#support_mounts
services:
  web:
    image: python:3.9-alpine
#    volumes:
#      - ./app:/app
    working_dir: /app
    command: python -m http.server 8000

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - web
